server:
  port: 9999

#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    config:
      uri: http://localhost:8765/ 
      
management:
  endpoints: 
    web: 
      exposure: 
        include: hystrix.stream
        
        


        