server:
 port: 1298

#eureka:
 # client:
  #  serviceUrl:
   #   defaultZone: http://localhost:8761/eureka
 

 
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/project_management?useSSL=false&serverTimezone=UTC
    username: root
    password: pass@word1
    
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
    show-sql: true
  application:
    name: employee-service
  cloud:
    config:
      uri: http://localhost:8765/
     
