server:
  port: 9090
 
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_management
    username: root
    password: pass@word1 
#spring:
  #h2:
   # console:
      #enabled: true      
      
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/projectDescStakeDatabase

 # application:
  #  name: project-management
  #zipkin:
   # base-url: http://localhost:9411/
 # cloud:
  #  config:
   #   url: http=//localhost:8765/
  