server:
  port: 0
  
  
spring:
  application:
    name: manager-service
  cloud:
   config:
    uri: http://localhost:8765/
  datasource:
    url:  jdbc:mysql://localhost:3306/project_management?useSSL=false&serverTimezone=UTC
    username: root
    password: pass@word1
    
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
    show-sql: true  
  mail:
    host: smtp.gmail.com
    port: 587
    username: projectmng789sys@gmail.com 
    password: vanass@789
    properties:
      mail:
        smtp:
          starttls:
            enable: true
       
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/projectDescStakeDatabase

    
    