server:
  port: 1234
  
 
spring:
  datasource:
    url:  jdbc:mysql://project-management.cmbnvqzejn0j.us-east-2.rds.amazonaws.com:3306/project_management?useSSL=false&serverTimezone=UTC
    username: admin
    password: PassworD
    
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: none
    show-sql: true
  application:
    name: admin-service
  cloud:
   config:
     uri: http://localhost:8765/
  data:
    mongodb:
       uri: mongodb+srv://user1:zVcOiZnu2OByw56x@cluster0-egasi.mongodb.net/ProjectManagement?retryWrites=true&w=majority
      
     
 
  