server:
  port: 9090
 
#spring:
 # datasource:
  #  url: jdbc:mysql://localhost:3306/project_management
   # username: root
    #password: pass@word1 
spring:
  h2:
    console:
      enabled: true      
      
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true